apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: web
spec:
  containers:
  - name: nginx
    image: nginx:1.13
    ports:
    - name: web
      containerPort: 80
  - name: busybox
    image: docker.io/busybox:latest
    imagePullPolicy: IfNotPresent
    command: ["sleep","3600"]
    ports:
    - name: web
      containerPort: 81